config/routes.rb
Joyfoodly::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { registrations: :registrations, passwords: :passwords, confirmations: :confirmations }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :recipe_redirects, only: :show
  resources :foods, only: [:index, :show], path: 'classroom' do
    resources :recipes, only: [] do
      get 'print_view'
    end
    get ':recipe_slug' => 'comment_thread_sources#show'
    get ':recipe_slug/comments' => 'comments#index'
  end
  resources :users, only: [:edit, :update] do
    get 'change_password', on: :member
    get 'edit_account'
    patch 'update_account'
  end

  resources :payments
  get '/gift', to: 'payments#gift', as: 'new_gift'
  post '/gift', to: 'payments#create_gift', as: 'gifts'


  resources :shopping_lists, only: [:create, :edit, :update, :show, :destroy]
  resources :shopping_list_emails, only: :create
  resources :seasons, only: :update
  resource :parent_resources, only: :show
  resource :videos, only: :show
  resource :class_schedule
  resources :pages, only: :show
  resources :wait_lists, only: [:new, :create, :show]
  resources :testing_signup, only: :index
  resources :contact_forms, only: :create
  resources :forms, only: [:create, :show] do
    get 'submitted', on: :member
  end
  get 'almost_there' => 'home#confirmation_sent', as: :confirmation_sent
  get 'community_sessions' => 'community_sessions#show'

  resources :recipes, only: [:show]

  resources :upgrades, only: [:index, :create, :show]

  root to: 'home#rootpage'

  get '/coupons/:partner_id' => 'coupons#show'
  get '/su/:partner_id' => 'coupons#sign_up', as: 'gift_sign_up'
  get "/about" => "home#page"
  # catch all to enable marketing links
  get '/:tracking_slug' => 'home#marketing'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ActionView::Helpers::NumberHelper
  def confirmation_sent
  end

  def page
    # Handle specific slugs
    if /^\/about/.match(request.fullpath)
      set_price
      render 'about', layout: 'qubico'
    else
      # Unknown slug - go to root page - purists would insist this should be a 404.
      rootpage
    end
  end
  
  def rootpage
    set_price
    render layout: 'plain'
  end

  def marketing
    # Enable marketing slugs
    if params[:tracking_slug]=='clear'
      session[:partner_id]=nil
    else
      session[:partner_id]=params[:tracking_slug]
    end
    redirect_to :root
  end
end

app/views/home/_feature_image.html.haml
.col-xs-2.col-sm-2.col-md-1.featurebox
  .box-image
    = image_tag image_filename, class: 'img-responsive'

app/views/home/about.html.haml
/ -- ==============================================
/		MAIN NAV

#main-nav.navbar.navbar-fixed-top
  .container
    .navbar-header
      %button{type: "button", class: "navbar-toggle", "data-toggle" => "collapse", "data-target" => "#site-nav"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      <!-- ======= LOGO ========-->
      %a.navbar-brand{href: "/"}
        %span.logo-small
          = image_tag 'qubico/joyful12-logo-small.png'

        <!-- ==== Image Logo ==== -->
        <!--<img class="site-logo" src="/assets/qubico/logo.png" alt="logo" />-->

    #site-nav.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right.row
        %li.hidden-sm
          %a.scrollto{href: "#chefhollie"}
            Chef Hollie
        %li.hidden-sm
          %a.scrollto{href: "#reviews"}
            Reviews
        %li.hidden-sm
          %a.scrollto{href: "#tour"}
            Tour
        %li.hidden-sm
          %a.scrollto{href: "#contact"}
            Contact
        %li.hidden-sm.hidden-xs
          %a.color{href: "http://www.joyfoodly.com/blog", target: "_blank"}
            Blog
    <!--End navbar-collapse -->

  <!--End container -->

<!--End main-nav -->
<!-- ==============================================
Chef Hollie
=============================================== -->
%section#chefhollie.color-bg.light-typo.padding-top-bottom.top-section.cta-iphones
  %div.container

    - if params[:message].present?
      %p.text-warning.col-md-offset-5.btn.btn-warning
        = params[:message]

    %div.row

      %div.col-sm-4

        %div.ipad-frame.scrollimation.fade-up

          = image_tag 'qubico/hollie-5.png', class: 'img-responsive img-center'

          %div.ipad-screen.ipad-slider

            %ul.slides

              %li
                = image_tag 'qubico/hollie-6.png', class: 'img-responsive'
              %li
                = image_tag 'qubico/hollie-7.png', class: 'img-responsive'

      %div.col-sm-8
        %h2
          Learn From Chef Hollie
        %p
          The Joyful 12 was created by Chef Hollie Greene as a way to support families in eating more fruits and veggies (and help them enjoy the experience!)
        %p
          Hollie has worked with over 2,000 parents and children across the country, and knows that kids love eating fruits and vegetables. After attending the French Culinary Institute
          of New York City, Hollie worked with non-profits to develop programs that help get kids excited about vegetables.
        %p
          In the Joyful 12, Hollie will walk you through basic principles on introducing children to new foods, tips on how to get kids involved in the kitchen, and all kinds of resources to
          make you a more confident home cook. She believes in flavor and fun above all else in the kitchen, which is what you get with the Joyful 12!
          = link_to new_user_registration_path, class: 'btn btn-qubico white' do
            %i.fa.fa-arrow-down.signup_button
              Sign Up Now!  

// ==============================================
// RESPONSIVE VIDEO

%section.gray-bg.padding-top-bottom.hidden-xs
  %div.container
    %h1.section-title
      The Joyful 12 is for Busy Families
    %p.section-description
      You can make great food with Chef Hollie's support.

    %div.row

      .col-sm-10.col-sm-offset-1
        .macbook-frame
          = image_tag 'qubico/macbook2.png', class: 'img-responsive img-center'

          .macbook-screen
            %iframe{width: "640", height: "360", src: "//player.vimeo.com/video/88189339?color=4196b4", frameborder: "0", allowfullscreen: true}

//-- ==============================================
// Reviews
//==============================================

%section#reviews.white-bg.padding-top-bottom

  .container

    %h1.section-title
      Real Families Are Excited
    %p.section-description
      Take their word for it!

    .row.team-member
    
      .col-sm-3.col-sm-offset-1.member-thumb.scrollimation.fade-right

        = image_tag 'qubico/jean.png', class: 'img-responsive img-center'
        %h4
          Jean
        %p.title
          Aunt of 2 in Minneapolis, MN

      .col-sm-7.scrollimation.fade-left

        .member-details
          %p 
            Our niece and nephew were both asking for more broccoli after this fresh take of Mac 'n Cheese.

    .row.team-member.right
    
      .col-sm-3.col-sm-push-8.member-thumb.scrollimation.fade-left

        = image_tag 'miguel.jpg', class: 'img-responsive img-center'
        %h4
          Miguel
        %p.title
          Father of 3 in Novato, California

      .col-sm-7.col-sm-pull-2.scrollimation.fade-right

        .member-details
          %p 
            Joyful 12 has taught me that you do not have begin with a love for cooking to enjoy cooking. Everyone will gain their own appreciation when learning and preparing the simple, delicious Joyful 12 meals. Mine is being satisfied that my children are not only learning a life skill that will nourish them the rest of their lives, but they are doing it humanely for themselves and for the environment by considering veggies and fruits as their first source of food.
          %p
          %a{href: "http://www.joyfoodly.com/miguel", target: "_blank"}
            Read more about Miguel

    .row.team-member

      .col-sm-3.col-sm-offset-1.member-thumb.scrollimation.fade-right

        = image_tag 'qubico/augusta.png', class: 'img-responsive img-center'
        %h4
          Augusta
        %p.title
          Mother of 2 in South Carolina


      .col-sm-7.scrollimation.fade-left

        .member-details
          %p
            We made the dreamy greenie quesadillas tonight. They were fabulous! Even my son loved them and I
            thought the greens would be a hard sell. They were really filling so I have leftovers for lunch.
            And I love that avocado sauce…I could eat that everyday. We're having fun trying the Joyful 12
            recipes. The kids are always willing to try something new if I tell them it's your recipe.</p>


// -- ==============================================
// CALL TO ACTION
// ===============================================
%section.color-bg.light-typo.cta.hidden-xs

  .container

    .row
      .col-md-9.cta-message.col-sm-8
        %p
          %strong
            The Joyful 12
          is a year of eating in season with Chef Hollie. Busy families get access to 144 recipes, video tutorials,
          a community forum, parent resources, and more!

      .col-md-3.cta-button
        %p.text-center
          = link_to new_user_registration_path, class: 'btn btn-qubico white' do
            %i.fa.fa-arrow-down.signup_button
              Sign Up Now!  


= render 'shared/tour'

// -- ==============================================
// CALL TO ACTION
// ===============================================

%section.color-bg.light-typo.cta
  .container

    .row
      .col-sm-6.hidden-xs
        %a{href: 'http://www.joyfoodly.com/schoolproject/'}
          = image_tag 'qubico/hollie-3.png', class: 'img-responsive', style: 'margin: auto'
          
      .col-sm-6.col-xs-12
        %h2{style: 'margin-top: 0px'}
          How the Joyful 12 Project Improves the Health of School Communities
        %p
          The Joyful 12 Project aims to improve the health of our children by providing cooking education to every parent, teacher, and child in School Communities through a lifetime membership to the Joyful 12.
          
        %p
          Schools, through their Cafeterias and Classrooms, are healthier today because of the work being done by individuals and organizations that care about our children’s health. But little to no support has been provided to parents to help make learning about healthy habits at home fun and engaging. We can create sustainable healthy food habits by supporting parents with access to education and resources in their own homes.

        %h3
          How you can get involved

        %p
          Feel great knowing that every purchase you make provides lifetime access to a family in our Joyful 12 School Projects.
        %p
          Want to do even more? You can
          %a{href: 'http://www.joyfoodly.com/schoolproject/'}
            donate directly to the Joyful 12 School Project to help us grow healthy kids at school
        

// <!-- ==============================================
// CONTACT
// ===============================================

%section#contact.gray-bg.padding-top-bottom

  .container

    %h1.section-title
      We'd Love to Hear from You!
    %p.contact-description
      Do you have questions or feedback? Let us know!
    .col-md-offset-5.col-sm-6.col-sm-offset-4.hidden-xs
      %span.social-blue
        %a{href: image_url('http://www.facebook.com/joyfoodly'), target: "_blank"}
          = image_tag 'qubico/facebook.png'
      %span.social-blue
        %a{href: image_url('http://www.pinterest.com/joyfoodly'), target: "_blank"}
          = image_tag 'qubico/pinterest.png'
      %span.social-blue
        %a{href: image_url('http://www.instagram.com/joyfoodly'), target: "_blank"}
          = image_tag 'qubico/instagram.png'
      %span.social-blue
        %a{href: image_url('https://plus.google.com/+Joyfoodly'), target: "_blank"}
          = image_tag 'qubico/google.png'
      %span.social-blue
        %a{href: image_url('http://www.twitter.com/joyfoodly'), target: "_blank"}
          = image_tag 'qubico/twitter.png'
      %span.social-blue
        %a{href: image_url('http://www.vimeo.com/joyfoodly'), target: "_blank"}
          = image_tag 'qubico/vimeo.png'

    .row
      .col-sm-4.col-sm-offset-2.text-center.contact-item.scrollimation.fade-right.hidden-xs

        .icon
          %i.glyphicon.glyphicon-pushpin
        %h2
          Our Location
        %p
          San Francisco, CA

      .col-sm-4.text-center.contact-item.scrollimation.fade-left

        .icon
          %i.glyphicon.glyphicon-envelope
        %h2
          Email Us
        %p
          hollie@joyfoodly.com

    .row

      = form_tag contact_forms_path, id: 'contact-form', class: 'col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2' do
        .form-group
          = label_tag :name, class: 'control-label'
          .controls
            = text_field_tag :name, '', placeholder: 'Your name', class: 'form-control requiredField label_better',                          required: true
            %i.fa.fa-user

        .form-group
          = label_tag :email, class: 'control-label'
          .controls
            = email_field_tag :email, '', placeholder: 'Your email', class: 'form-control requiredField label_better',                                       required: true
            %i.fa.fa-user

        .form-group
          = label_tag :name, class: 'control-label'
          .controls
            = text_field_tag :subject, '', placeholder: 'Subject', class: 'form-control requiredField label_better',              required: true
            %i.fa.fa-user

        .form-group
          = label_tag :name, class: 'control-label'
          .controls
            = text_area_tag :message, '', placeholder: 'Your Message',                                class: 'form-control requiredField label_better', rows: '6', required: true 
            %i.fa.fa-user
                
        %p
          = button_tag "Send Message", class: "btn btn-qubico btn-block js-submit", data: {error_message: "Error!",          sending_message: "Sending...", ok_message: "Message Sent" }

// <!-- ==============================================
// FOOTER
// ===============================================
%footer#main-footer.color-bg.light-typo

  .container.text-center
    %ul.social-links
      = render partial: 'social_link', locals: {uri: 'http://www.facebook.com/joyfoodly', img: 'qubico/facebook-white.png'}
      = render partial: 'social_link', locals: {uri: 'http://www.twitter.com/joyfoodly', img: 'qubico/twitter-white.png'}
      = render partial: 'social_link', locals: {uri: 'https://plus.google.com/+Joyfoodly', img: 'qubico/google-white.png'}
      = render partial: 'social_link', locals: {uri: 'http://www.pinterest.com/joyfoodly', img: 'qubico/pinterest-white.png'}
      = render partial: 'social_link', locals: {uri: 'http://www.instagram.com/joyfoodly', img: 'qubico/instagram-white.png'}
      = render partial: 'social_link', locals: {uri: 'http://www.vimeo.com/joyfoodly', img: 'qubico/vimeo-white.png'}

    %p
      &copy;2014
      %a{href: "http://www.joyfoodly.com", target: "_blank"}
        JoyFoodly
      , LLC.

app/views/home/confirmation_sent.html.erb
<h1 class="text-center">Almost there!</h1>
<% if @shareable_tag == 'lusutton' %>
  <p class="large-text text-center">Please take a moment to <a href='https://www.surveymonkey.com/s/7S7SCH6'>fill in our survey</a></p>
  <p class="large-text text-center">Favor de tomar un momento para <a href='https://www.surveymonkey.com/s/7S5BC9Y'>llenar nuestra encuesta</a> en espa&#241;ol</p>
  <p class='fineprint-text'>Privacy Notice: The Joyful 12 School Project is not collecting personal private data about its members. Data collected is used solely for the purposes of project implementation, monitoring and evaluation; and are entirely anonymous and aggregate level data.</p>
<% end %>
<ul class="nav row">
  <li class="col-md-1 col-md-offset-2">
    <img alt="spinach" class="img-responsive wiggle hidden-xs" height="101" src="/assets/nav-food-images/spring-spinach-f109b6321abc4f9c80b071e19e8ce2b2.png" width="68">
  </li>
  <li class="col-md-1">
    <img alt="greens" class="img-responsive wiggle hidden-xs" height="101" src="/assets/nav-food-images/summer-greens-ce67f3a1a8b3b270cff6129087f4162a.png" width="68">
  </li>
  <li class="col-md-1">
    <img alt="potato" class="img-responsive wiggle hidden-xs" height="101" src="/assets/nav-food-images/spring-potato-c481106edd51da9f6acd6a90a2abc41a.png" width="68">
  </li>
  <li class="col-md-1">
    <img alt="peas" class="img-responsive wiggle hidden-xs" height="101" src="/assets/nav-food-images/spring-peas-ae8dde80021fa80a81bf28a286f4111d.png" width="68">
  </li>
  <li class="col-md-1">
    <img alt="summer squash" class="img-responsive wiggle hidden-xs" height="101" src="/assets/nav-food-images/summer-squash-81694469ee7dc4edadee9f592f764d90.png" width="68">
  </li>
  <li class="col-md-1">
    <img alt="strawberry" class="img-responsive wiggle hidden-xs" height="101" src="/assets/nav-food-images/spring-strawberry-cabc81d611d62123fef24b6a082dd3ed.png" width="68">
  </li>
  <li class="col-md-1">
    <img alt="eggplant" class="img-responsive wiggle hidden-xs" height="101" src="/assets/nav-food-images/summer-eggplant-3815c31d5ec18e83e2dd8bb6ee1229e9.png" width="68">
  </li>
  <li class="col-md-1">
    <img alt="pepper" class="img-responsive wiggle hidden-xs" height="101" src="/assets/nav-food-images/summer-pepper-c2e3ee0b2bfd100a79052fa51b66ea41.png" width="68">
  </li>
</ul>

<div class="col-xs-12 hidden-md hidden-lg hidden-xl">
<img alt="greens" class="wiggle centered" src="http://d3uroln2zt6ogz.cloudfront.net/pages/media/original/bbad62625cf58b33b3cd0aece555063132c0f985.png?1403730648" width="68">
</div>


<div class="row">
<h3>
<ol class="col-md-5 col-md-offset-4 col-xs-8 col-xs-offset-4">
  <li>Check Your Email For A Confirmation Link</li>
  <br />
  <li>Click The Link To Confirm Your Account</li>
  <br />
  <li>Start Cooking!</li>
</ol>
</h3>
</div>

app/views/home/rootpage.html.haml
.rootpage
  .row.navrow
    .col-xs-1
    .col-xs-2
      = image_tag "joyful12logo.png", class: 'logoimage'
    .col-xs-2
    .hidden-sm.hidden-md.hidden-lg
      .col-xs-2.col-xs-offset-4
        = image_tag 'hamburger icon.jpg', id: 'hamburger_icon'
    .hidden-xs#loginbox
      = form_tag('/users/sign_in', id: 'signin_form') do
        .col-sm-3.col-xs-7
          %input.textinput#email_field{name: 'user[email]', placeholder: 'Email', style: 'width: 90%; float: right;'}  
        .col-sm-4.col-xs-5
          .password-box
            %input.textinput#password_field{name: 'user[password]', type: 'password', placeholder: 'Password', style: 'display: inline'}
            #signin-box
              SIGN IN
            .forgot-password
              =link_to 'Forgot Password?', '/users/password/new'
  .row.messagerow
    .col-md-offset-4.col-md-4
      = render 'shared/flash'

  .row.herorow
    .col-xs-12.col-sm-6.leftherocolumn
      .leftherocolumntext
        .bold-text.titletext
          %br
          = HomePageFeature.get_feature_switched(:general_welcome_message, session)
          // Making this raw because we'll have html in it
        .subtext.hidden-xs
          = raw(HomePageFeature.get_feature(:welcome_bullets))
    .col-xs-12.col-sm-6
      .rightcolumntext
        = image_tag "screen_shapes_trans.gif", class: 'img-responsive heroimage', style: 'margin: auto; min-height: 200px'
        .price_circle
          .vertical-third
          .vertical-third.bubble-third-middle
            = pp_price(@price, 0)
          .vertical-third
        .center-div
          = HomePageFeature.get_feature_switched(:rightcolumn_subtext, session)
        .center-div
          = link_to new_user_registration_path, class: 'stripe-button-el', id: 'zero-price-button' do
            <span>START COOKING NOW!</span>

        .gift-div
          = link_to 'Or give the gift of Joyful 12 <span class="glyphicon glyphicon-gift" aria-hidden="true"></span>'.html_safe,
            new_gift_path, class: 'gift'

  .row.section
    .col-xs-12
      .center-div.limited-width.bold-text.feature-title
        = raw(HomePageFeature.get_feature(:section_title_one))
    .row
      .col-xs-12
        .center-div.blueline

  .row.section
    .center-div.limited-width
      = HomePageFeature.get_feature(:section_subtext_one)

  .section.bottom-buffer
    .row
      .col-xs-2.hidden-sm.hidden-md.hidden-lg
      .col-sm-1.col-md-2.hidden-xs

      = render partial: 'feature_image', locals: {image_filename: 'circle_images/pink radish.png'}
      
      .col-xs-6.col-sm-3.featurebox
        .box-header.bold-text
          = HomePageFeature.get_feature :box11_header
        .box-text
          = HomePageFeature.get_feature :box11_text
      .col-xs-2.hidden-sm.hidden-md.hidden-lg

      .second-col-arrange
        .col-xs-2.hidden-sm.hidden-md.hidden-lg{style: 'clear: left;'}

        = render partial: 'feature_image', locals: {image_filename: 'circle_images/just hollie.png'}          

        .col-xs-6.col-sm-3.featurebox
          .box-header.bold-text
            = HomePageFeature.get_feature :box12_header
          .box-text
            = HomePageFeature.get_feature :box12_text
        .col-sm-1.col-md-2.hidden-xs
        .col-xs-2.hidden-sm.hidden-md.hidden-lg

    .row.top-buffer.xs-remove-buffer
      .col-xs-2.hidden-sm.hidden-md.hidden-lg
      .col-sm-1.col-md-2.hidden-xs

      = render partial: 'feature_image', locals: {image_filename: 'circle_images/ingredients.png'}
          
      .col-xs-6.col-sm-3.featurebox
        .box-header.bold-text
          = HomePageFeature.get_feature :box21_header
        .box-text
          = HomePageFeature.get_feature :box21_text
      .col-xs-2.hidden-sm.hidden-md.hidden-lg

      .second-col-arrange
        .col-xs-2.hidden-sm.hidden-md.hidden-lg{style: 'clear: left;'}

        = render partial: 'feature_image', locals: {image_filename: 'circle_images/hollie with kids.png'}
        
        .col-xs-6.col-sm-3.featurebox
          .box-header.bold-text
            = HomePageFeature.get_feature :box22_header
          .box-text
            = HomePageFeature.get_feature :box22_text
        .col-sm-1.col-md-2.hidden-xs
        .col-xs-2.hidden-sm.hidden-md.hidden-lg

  // End of main features

  .row.section.bottom-buffer
    .center-div.holliebox.limited-width
      = link_to 'Learn more about Joyful 12 and Chef Hollie!', '/about'

  = render 'shared/tour'

  .row.footerrow.top-padding.bottom-padding
    .center-div
      %span.social-icon
        %a{href: 'http://www.facebook.com/joyfoodly'}
          =image_tag 'qubico/facebook-white.png'
      %span.social-icon
        %a{href: 'http://www.pinterest.com/joyfoodly'}
          =image_tag 'qubico/pinterest-white.png'
      %span.social-icon
        %a{href: 'http://www.instagram.com/joyfoodly'}
          =image_tag 'qubico/instagram-white.png'
      %span.social-icon
        %a{href: 'https://plus.google.com/+Joyfoodly'}
          =image_tag 'qubico/google-white.png'
      %span.social-icon
        %a{href: 'http://www.twitter.com/joyfoodly'}
          =image_tag 'qubico/twitter-white.png'
      %span.social-icon
        %a{href: 'http://www.vimeo.com/joyfoodly'}
          =image_tag 'qubico/vimeo-white.png'
      %p
        &copy;2014
        %a{href: "http://www.joyfoodly.com", target: "_blank"}
          JoyFoodly
          , LLC.