config/routes.rb
Joyfoodly::Application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { registrations: :registrations, passwords: :passwords, confirmations: :confirmations }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :recipe_redirects, only: :show
  resources :foods, only: [:index, :show], path: 'classroom' do
    resources :recipes, only: [] do
      get 'print_view'
    end
    get ':recipe_slug' => 'comment_thread_sources#show'
    get ':recipe_slug/comments' => 'comments#index'
  end
  resources :users, only: [:edit, :update] do
    get 'change_password', on: :member
    get 'edit_account'
    patch 'update_account'
  end

  resources :payments
  get '/gift', to: 'payments#gift', as: 'new_gift'
  post '/gift', to: 'payments#create_gift', as: 'gifts'


  resources :shopping_lists, only: [:create, :edit, :update, :show, :destroy]
  resources :shopping_list_emails, only: :create
  resources :seasons, only: :update
  resource :parent_resources, only: :show
  resource :videos, only: :show
  resource :class_schedule
  resources :pages, only: :show
  resources :wait_lists, only: [:new, :create, :show]
  resources :testing_signup, only: :index
  resources :contact_forms, only: :create
  resources :forms, only: [:create, :show] do
    get 'submitted', on: :member
  end
  get 'almost_there' => 'home#confirmation_sent', as: :confirmation_sent
  get 'community_sessions' => 'community_sessions#show'

  resources :recipes, only: [:show]

  resources :upgrades, only: [:index, :create, :show]

  root to: 'home#rootpage'

  get '/coupons/:partner_id' => 'coupons#show'
  get '/su/:partner_id' => 'coupons#sign_up', as: 'gift_sign_up'
  get "/about" => "home#page"
  # catch all to enable marketing links
  get '/:tracking_slug' => 'home#marketing'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  
  validates :amount,      presence: true, numericality: { greater_than: 0 }
  validates :card_token,  presence: true
  validates :product_id,  presence: true, inclusion: { in: %w[beta season year] }
  validate :create_stripe_customer
  validate :create_stripe_charge
  validates :customer_id, presence: true
  validates :charge_id,   presence: true
  validate :has_email

  attr_writer :email, :coupon
  attr_accessor :gift
  
  private

  def create_stripe_customer
    return if errors.present?
    if user && user.payment_gateway_customer_id.present?
      self.customer_id = user.payment_gateway_customer_id
    else
      customer = Stripe::Customer.create(
        email: user_email,
        source: card_token,
        metadata: { user_id: user_id },
      )
      self.customer_id = customer.id
      user.update_attribute(:payment_gateway_customer_id, customer.id) if user
    end
  rescue Stripe::StripeError => error
    errors[:stripe] << error.message
  end

  def create_stripe_charge
    return if errors.present?
    charge = Stripe::Charge.create(
      customer: customer_id,
      amount: amount,
      description: "Joyful 12 #{product_id}",
      currency: 'usd',
    )
    self.charge_id = charge.id
  rescue Stripe::StripeError => error
    errors[:stripe] << error.message
  end

  def user_id
    user.id if user
  end

  def user_email
    user ? user.email : @email
  end

  def coupon
    @coupon || (user.coupons.first if user)
  end

  def has_email
   errors.add(:base, 'payment must have email') unless user_email
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!, except: [:gift, :create_gift]
  before_action :skip_signed_up_users, except: [:gift, :create_gift]
  before_action :set_price

  def new
    render layout: 'sign_up_flow'
  end

  def gift
    @gift = Gift.new
    render layout: 'sign_up_flow'
  end

  def create_gift
    @gift = Gift.new(gift_params)
    @gift.giver_id = current_user
    if @gift_price > 0
      @payment = build_gift_payment
      if @gift.valid? && @payment.valid?
        ActiveRecord::Base.transaction do
          @gift.save
          @payment.save(validate: false)
        end
        flash[:notice] = "Thanks for your purchase!"
        redirect_to root_path
      else
        errors = @payment.errors[:stripe] + @gift.errors.full_messages
        flash.now[:alert] = errors.to_sentence
        render 'gift', layout: 'sign_up_flow'
      end
    else
      if @gift.valid?
        @gift.save
        flash[:notice] = "Thanks for your purchase!"
        redirect_to root_path
      else
        errors = @gift.errors.full_messages
        flash.now[:alert] = errors.to_sentence
        render 'gift', layout: 'sign_up_flow'
      end
    end
  end

  def create
    @payment = current_user.payments.build(payment_params)
    @payment.amount = @price
    if @payment.save
      current_user.update(signed_up: true)
      redirect_to after_sign_in_path_for(current_user)
    else
      flash.now[:alert] = @payment.errors[:stripe].to_sentence
      render 'new', layout: 'sign_up_flow'
    end
  end

  private

  def gift_params
    p = params.require(:gift).permit(:your_name, :your_email, :message, :their_email)
    p[:price] = @gift_price
    p
  end

  def payment_params
    {
      card_token: params[:stripeToken],
      product_id: 'season'
    }
  end

  def build_gift_payment
    payment = Payment.new(payment_params)
    payment.email = @gift.your_email
    payment.coupon = found_coupon?
    payment.gift = true
    payment.amount = @gift_price
    payment.user_id = current_user.try(:id) || -1
    payment
  end

  def skip_signed_up_users
    redirect_to after_sign_in_path_for(current_user) if current_user.signed_up?
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def months
    Date::MONTHNAMES.compact.each_with_index.map { |name,i| ["#{i + 1} - #{name}", i + 1] }
  end

  def years
    (Date.today.year..(Date.today.year + 20)).to_a
  end
end

app/views/payments/gift.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-md-4'>
      <h2 class='form-signup-header'>Give the gift of Joyful 12</h2>
      <%= render 'shared/flash' %>
      <%= form_for(@gift, html: { id: 'payment-form' }) do |f| %>
        <div class='gift-form'>
          <div class="form-group">
            <%= f.label :your_name%><br />
            <%= f.text_field :your_name, value: @gift.your_name || current_user.try(:full_name), autofocus: true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :your_email %><br />
            <%= f.text_field :your_email, value: @gift.your_email || current_user.try(:email), autofocus: true, class: 'form-control' %>
            <p class="help-block">This is where you'll receive your receipt.</p>
          </div>

          <div class="form-group">
            <%= f.label :message, 'Message (Optional)' %><br />
            <%= f.text_area :message, autofocus: true, class: 'form-control' %>
          </div>

          <h3>Gift Receiver</h3>
          <div class="form-group">
            <%= f.label :their_email%><br />
            <%= f.text_field :their_email, autofocus: true, class: 'form-control' %>
          </div>

          <%= render 'shared/coupon' %>

          <% if @gift_price > 0 %>
            <%= render 'shared/payment_errors' %>
            <div class='billing-info'>
              <%= javascript_include_tag "https://js.stripe.com/v2/" %>
              <script>
                Stripe.setPublishableKey("<%= Rails.application.secrets.stripe_publishable_key %>");
              </script>
              <h3>Billing Info</h3>
              <div class="form-group">
                <%= label_tag :credit_card_number %><br />
                <%= text_field_tag :credit_card_number, nil, autofocus: true, id: nil, name: nil, class: 'form-control', data: { stripe: 'number' } %>
              </div>

              <div class="form-group">
                <%= label_tag :cvc, 'CVC'%><br />
                <%= text_field_tag :cvc, nil, autofocus: true, id: nil, name: nil, class: 'form-control', data: { stripe: 'cvc' } %>
              </div>

              <div class='form-inline'>
                <div class="form-group">
                  <%= label_tag :expiration_month %><br />
                  <%= select_tag :expiration_month, options_for_select(months), autofocus: true, id: nil, name: nil, class: 'form-control',
                    data: { stripe: 'exp-month' } %>
                </div>

                <div class="form-group">
                  <%= label_tag :expiration_year %><br />
                  <%= select_tag :expiration_year, options_for_select(years), autofocus: true, id: nil, name: nil, class: 'form-control',
                    data: { stripe: 'exp-year' } %>
                </div>
              </div>
            </div>
          <% end %>
          <h3>Total Amount To Be Charged: <span class="gift-price"><%= pp_price(@gift_price) %></span>.</h3>

          <%= submit_tag('Gift Joyful 12!', class: 'give-gift btn btn-lg btn-primary btn-block toggler') %>
        </div>
      <% end %>
    </div>
    <%= render 'shared/registration_photo' %>
  </div>
</div>

app/views/payments/new.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/" %>
<script>
  Stripe.setPublishableKey("<%= Rails.application.secrets.stripe_publishable_key %>");
</script>
<div class='container-fluid'>
  <div class='row'>
    <div class='col-md-4'>
      <h2 class='form-signup-header'>Billing Information</h2>
      <%= render 'shared/flash' %>
      <%= form_tag(payments_path, id: 'payment-form') do %>
        <%= render 'shared/payment_errors' %>
        <div class='billing-info'>
          <div class="form-group">
            <%= label_tag :credit_card_number %><br />
            <%= text_field_tag :credit_card_number, nil, autofocus: true, id: nil, name: nil, class: 'form-control', data: { stripe: 'number' } %>
          </div>

          <div class="form-group">
            <%= label_tag :cvc, 'CVC' %><br />
            <%= text_field_tag :cvc, nil, autofocus: true, id: nil, name: nil, class: 'form-control', data: { stripe: 'cvc' } %>
          </div>

          <div class='form-inline'>
            <div class="form-group">
              <%= label_tag :expiration_month %><br />
              <%= select_tag :expiration_month, options_for_select(months), autofocus: true, id: nil, name: nil, class: 'form-control',
                data: { stripe: 'exp-month' } %>
            </div>

            <div class="form-group">
              <%= label_tag :expiration_year %><br />
              <%= select_tag :expiration_year, options_for_select(years), autofocus: true, id: nil, name: nil, class: 'form-control',
                data: { stripe: 'exp-year' } %>
            </div>
          </div>

          <h3>Total Amount To Be Charged: <span class="price"><%= pp_price(@price) %></span>.</h3>
          <%= button_tag('Subscribe to Joyful 12!', id: 'create-account', class: 'btn btn-lg btn-primary btn-block toggler') %>
        </div>
      <% end %>
    </div>
    <%= render 'shared/registration_photo' %>
</div>